apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-api
  namespace: simple-api
spec:
  selector:
    matchLabels:
      app: simple-api # has to match .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: simple-api # has to match .spec.selector.matchLabels
    spec:
      containers:
        - name: simple-api
          image: doniyozov/api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: simple-api-internal
  labels:
    app: simple-api
    service: simple-api
spec:
  ports:
    - port: 5005
      targetPort: 80 #this port should match with the port application is targetting in this case: containerPort: 80.
      protocol: TCP
