apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleapi
  namespace: back-end
spec:
  selector:
    matchLabels:
      app: simpleapi # has to match .spec.template.metadata.labels
  serviceName: simpleapi
  template:
    metadata:
      labels:
        app: simpleapi # has to match .spec.selector.matchLabels
    spec:
      containers:
        - name: simpleapi
          image: hub.docker.com/doniyozov/api:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: simpleapi
  namespace: api
spec:
  type: LoadBalancer
  selector:
    app: simpleapi
  ports:
    - port: 80 #his  port is the port which belongs to ClusterIP which will be exposed
      targetPort: 80 #this port should match with the port application is targetting in this case: containerPort: 8002.
      nodePort: 30009
      protocol: TCP
