apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-api
  namespace: back-end
spec:
  selector:
    matchLabels:
      app: simple-api # has to match .spec.template.metadata.labels
  serviceName: simple-api
  template:
    metadata:
      labels:
        app: simple-api # has to match .spec.selector.matchLabels
    spec:
      containers:
        - name: simple-api
          image: hub.docker.com/doniyozov/api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: simpleapi-internal-service
  labels:
    app: simpleapi
    service: simpleapi
spec:
  type: LoadBalancer
  ports:
    - port: 5005
      targetPort: 80 #this port should match with the port application is targetting in this case: containerPort: 80.
      nodePort: 30010 # this should be in from range: 30000 - 32767
      protocol: TCP
  selector:
    service: simpleapi #This should match with Pod label
